version: "3"
services:
  nginx-proxy:
    image: nginx:mainline-alpine
#    image: nginx-proxy:latest
    container_name: proxy-app
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl_cert:/etc/ssl
    ports:
      - "8080:80"
#    networks:
#      - nodejs-app_frontend_net
#    environment:
      #PORT: ${PORT}
#      WAIT_HOSTS: node-app:5000
#    depends_on:
#      - node-app
#networks:
#  nodejs-app_frontend_net:
#    external: true